# Generated by Django 4.0.3 on 2022-03-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farm', '0002_basket_order_product_producttype_user_delete_farm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='information',
            field=models.CharField(default='Product from A.O Farm', max_length=255),
        ),
    ]
